changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Novinky 🎉
      labels:
        - "t:enhancement"
    - title: Opravy chyb 🪲
      labels:
        - "t:bug"
    - title: Ostatní změny
      labels:
        - "*"