export const optionsInputsC = [
    'nevyužito',
    'venkovní',
    'zóna 1',
    'zóna 2',
    'Z1 topná',
    'Z2 topná',
    'AKU',
    'TV',
    'Vratka TČ',
    'Výstup TČ',
    'TV spodní',
    'AKU spodní',
    'pok.jed. Z2',
    'krb',
    't2 modul krb',
    't1 modul uni',
    't2 modul uni',
    'solár',
    'zóna 3',
    'zóna 4',
    'zóna 5',
    'zóna 6',
    'Z3 topná',
    'Z4 topná',
    'Z5 topná',
    'Z6 topná',
    'pok.jed. Z3',
    'pok.jed. Z4',
    'pok.jed. Z5',
    'pok.jed. Z6',
    't1 modul uni2',
    't2 modul uni2',
    'čidlo zpátečky TČ1',
    'čidlo výstupu TČ1',
] as const
export const optionsInputsB = [
    'nevyužito',
    'iPWM vstup čerpadlo TČ1',
    'iPWM vstup čerpadlo TČ2',
    'iPWM vstup čerpadlo TČ3',
    'iPWM vstup čerpadlo TČ4',
    'iPWM vstup čerpadlo TČ5',
    'iPWM vstup čerpadlo TČ6',
    'iPWM vstup čerpadlo TČ7',
    'iPWM vstup čerpadlo TČ8',
    'iPWM vstup čerpadlo TČ9',
    'iPWM vstup čerpadlo TČ10',
    'iPWM vstup pro solární čerpadlo',
] as const
export const optionsOutputsF = [
    'nevyužito',
    'zdroj ON/OFF 2',
    'UNI funkce 1',
    'cirkulace TV',
    'čerpadlo KTP',
    'zóna 2 čerpadlo',
    'zóna 2 ventil otvírá',
    'zóna 2 ventil zavírá',
    'chlazení 1',
    'UNI funkce 2',
    'čerpadlo TČ 1',
    'solární čerpadlo',
    'ventil solárního spotřebiče 2',
    'ventil solárního spotřebiče 3',
    'ohřev TV z AKU',
    'alarm',
    'rozšířená příprava TV',
    'zóna 1 čerpadlo',
    'zóna 1 ventil otvírá',
    'zóna 1 ventil zavírá',
    'místnost 1',
    'místnost 2',
    'místnost 3',
    'místnost 4',
    'zóna 3 čerpadlo',
    'zóna 3 ventil otvírá',
    'zóna 3 ventil zavírá',
] as const
export const optionsOutputsB = [
    'nevyužito',
    'PWM pro čerpadlo TČ1',
    'PWM pro čerpadlo TČ2',
    'PWM pro čerpadlo TČ3',
    'PWM pro solární čerpadlo',
    'doplňkový zdroj 0-10 V',
    'signál 0-10V do jednotky VZT',
    'řízení FVE top. tělesa na L1',
    'směšovací ventil 0-10V pro zónu 1',
    'směšovací ventil 0-10V pro zónu 2',
    'směšovací ventil 0-10V pro zónu 3',
    'řízení FVE top. tělesa na L2',
    'řízení FVE top. tělesa na L3',

] as const
export type OptionsInputsC = typeof optionsInputsC[number]
export type OptionsInputsB = typeof optionsInputsB[number]
export type OptionsOutputsF = typeof optionsOutputsF[number]
export type OptionsOutputsB = typeof optionsOutputsB[number]